### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by ushisantoasobu** [bannzai/Kuri#19]
Thank you for your nice tool!!

Could you tell me the way to debug for current latest version (0.3.3) ?

I read the [document](https://github.com/bannzai/Kuri/blob/master/Documents/debug.md) for debug, but I couldn't find `Kuri.xcodeproj` (it seems set in `.gitignore`).

**Comment by bannzai** [comment]
@ushisantoasobu 

Thanks for your question.
Sorry, This documantation is not updated.

You can make `Kuri.xcodeproj` using [Swift Package Manager](https://github.com/apple/swift-package-manager) and run `swift package generate-xcodeproj`.  
After run generate-xcodeproj command, you get `Kuri.xcodeproj` under the current directory and you can start debug.

**Comment by ushisantoasobu** [comment]
@bannzai 

Thank you for your help!!
Now I tried, and I could!!
(I am a beginner of SPM 🙇 )
